[2015-01-12 09:57:54,341] ERROR Unexpected error running tests
Traceback (most recent call last):
  File "./TestRunner.py", line 203, in run
    lineParser = parsers.LineParser(self.process.stderr)
AttributeError: 'NoneType' object has no attribute 'stderr'
[2015-01-12 10:04:01,985] ERROR Unexpected error running tests
Traceback (most recent call last):
  File "./TestRunner.py", line 203, in run
    lineParser = parsers.LineParser(self.process.stderr)
AttributeError: 'NoneType' object has no attribute 'stderr'
