[2015-01-12 11:44:41,930] ERROR Unexpected error running tests
Traceback (most recent call last):
  File "./TestRunner.py", line 203, in run
    lineParser = parsers.LineParser(self.process.stderr)
AttributeError: 'NoneType' object has no attribute 'stderr'
